trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: gitversion/setup@1
  inputs:
    versionSpec: '5.x'
- task: gitversion/execute@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)'
    useConfigFile: true
    configFilePath: 'gitversion.yml'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'SnowflakePS.csproj'
    workingDirectory: '$(Build.SourcesDirectory)'
    arguments: '/p:Configuration=$(BuildConfiguration)'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/bin/$(BuildConfiguration)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/sfsnowsight-extensions.$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/sfsnowsight-extensions.$(Build.BuildId).zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'

