name: Release artifacts

on:
  push:
    branches: [ "master" ]

jobs:
  Release:
    runs-on: macos-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v1.1.1
      with:
        versionSpec: '5.x'
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v1.1.1
      id: gitversion_step
      with:
        useConfigFile: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Update csproj version
      shell: pwsh
      env:
        gitVersion_assemblyVersion: ${{ steps.gitversion_step.outputs.AssemblySemVer }}
      run: Scripts/SetProjectVersion.ps1
    - name: Update pwsh module version
      shell: pwsh
      env:
        gitVersion_assemblyVersion: ${{ steps.gitversion_step.outputs.AssemblySemVer }}
      run: Scripts/SetModuleVersion.ps1
    - name: Dotnet Publish All
      run: ./PublishAll.ps1
      shell: pwsh
    - name: Zip All
      run: ./ZipReleases.ps1
      shell: pwsh
    - name: Tag the commit
      run: |
        next_version=${{ steps.gitversion_step.outputs.AssemblySemVer }}
        git tag -a "$next_version" -m "Version $next_version"
        git push --follow-tags
    - name: Creates a release in GitHub and uploads attachments
      run: |
        gh release create ${{ steps.gitversion_step.outputs.AssemblySemVer }} ./Releases/*.zip
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
    